---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: variant

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: var3

conditions:
  - allOf:
      - property:
          name: userId
          operator: in-array
          operands:
            - bgunasekaran@cloudbees.com
    flagValue: var2
