---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: zero8

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 90
    option: true
  - percentage: 10
    option: false

conditions: []
