---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tg-1

description: desc 2

conditions:
  allOf:
    - property:
        name: cp-boolean-1
        operator: is-false
