---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tg1

description: desc added for tg1 from scm

conditions:
  allOf:
    - property:
        name: cp1
        operator: is-undefined
