---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tg2

description: 

conditions:
  allOf:
    - property:
        name: name
        operator: regex
        operands:
            - 'sample '
