---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tgNumProp

description: 

conditions:
  allOf:
    - property:
        name: numProp
        operator: eq
        operands:
            - 216
