---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: livestream_feature_with_tg
flagType: boolean
description: ""
labels:

availableValues:
  - "false"
  - "true"

isPermanent: false
