---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: newFlag1
flagType: boolean
description: This flag was created with the following entites served from Postgres; flags, custom props, sdkkeys
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
